# Use the C base
language: c

# Switch to Ubuntu 14.04 Trusty beta instead of using the default 12.04 Precise
# this is required due to the dependency to libsdl2-dev
#sudo: required
#dist: trusty

# Linux - add the Ubuntu restricted tool chain to install GCC 5 and 6, also to
# install the development package for SDL2
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-5-multilib
            - g++-5-multilib
            - gcc-6-multilib
            - g++-6-multilib

matrix:
    # If something failed, stop
    fast_finish: true
    include:
        # Linux GCC 5
        - os: linux
          env: COMPILER=gcc-5
          compiler: gcc-5

install:
    # Prepare the dependencies, build and fake Steam common directories for Travis
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - STEAMCOMMON_DIR="${TRAVIS_BUILD_DIR}/steam_common"
    - SDL_DIR="${DEPS_DIR}/SDL2"
    - mkdir -p ${DEPS_DIR} && mkdir -p ${STEAMCOMMON_DIR} && mkdir -p ${STEAMCOMMON_DIR} && cd ${DEPS_DIR}
    # Get the latest CMake version
    - |
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        CMAKE_URL="http://www.cmake.org/files/v3.6/cmake-3.6.1-Linux-x86_64.tar.gz"
        SDL_FILE="libsdl2-dev_2.0.2+dfsg1-3ubuntu1_i386.deb"
        SDL_MIRROR="http://fr.archive.ubuntu.com/ubuntu/pool/universe/libs/libsdl2/${SDL_FILE}"
        mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
        travis_retry wget --no-check-certificate --quiet ${SDL_MIRROR}
        dpkg -x ${SDL_FILE} ${SDL_DIR}
        ls ${SDL_DIR}
        #export LD_LIBRARY_PATH=${SDL_DIR}:${LD_LIBRARY_PATH}
      else
        if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
      fi

before_script:
    # Move to build directory
    - cd ${TRAVIS_BUILD_DIR}
    - mkdir build && cd build

script:
    # Just execute the cmake and make commands
    - |
      if [[ "${COMPILER}" == "gcc-5" ]]; then
        cmake -DCMAKE_CXX_COMPILER="g++-5" -DCMAKE_C_COMPILER="gcc-5" -DSTEAMCOMMON=${STEAMCOMMON_DIR} -DSDL2=${SDL_DIR}/usr/lib/i386-linux-gnu/libSDL2-2.0.so ..
      fi
    - make

notifications:
    # Notify only if the status changed
    on_failure: change
    on_success: change

cache:
    # Avoid reinstalling GCC 5 and 6 (unless we clear the cache)
    directories:
        - .cache
    apt: true
