# Use a VM with VS 2015
os: Visual Studio 2015

# Only target Windows 32 bits
platform: Win32

# Build in both Debug and Release
configuration:
  - Debug
  - Release

# If one job fail, mark the build as failed
matrix:
  fast_finish: true

