# Use a VM with VS 2015
os: Visual Studio 2015

# Only target Windows 32 bits
platform: Win32

# Build in both Debug and Release
configuration:
  - Debug
  - Release

before_build:
  # Appveyor uses CMake 2.8, we require at least 3.6, so make the update
  - ps: Write-Host "=== (1/7) Downloading CMake 3.6.1 ZIP for Windows 64 bits ===" -foregroundcolor green
  - ps: wget https://cmake.org/files/v3.6/cmake-3.6.1-win64-x64.zip -OutFile cmake.zip
  - ps: Write-Host "=== (2/7) Installing CMake ===" -foregroundcolor green
  - cmd: 7z x cmake.zip -o"." -y

# If one job fail, mark the build as failed
matrix:
  fast_finish: true

# We don't have unit tests
test: off

# We don't do deploying
deploy: off
